// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN9oqcytf5mI1CoTXQW_M47TU8G5kkGA4',
    appId: '1:603224733477:web:d9198e121b1f1c1a8c8ccc',
    messagingSenderId: '603224733477',
    projectId: 'bukuraya-f3a47',
    authDomain: 'bukuraya-f3a47.firebaseapp.com',
    storageBucket: 'bukuraya-f3a47.firebasestorage.app',
    measurementId: 'G-L9YDHHKSSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEgrG_L4pMgrfEZApM2_plCId3ErYlAtY',
    appId: '1:603224733477:android:3983326b86b84aa38c8ccc',
    messagingSenderId: '603224733477',
    projectId: 'bukuraya-f3a47',
    storageBucket: 'bukuraya-f3a47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTTT009WV0mTVN_aQSK8iyop5qO5oT0Ok',
    appId: '1:603224733477:ios:af0ad4cdd2a03cea8c8ccc',
    messagingSenderId: '603224733477',
    projectId: 'bukuraya-f3a47',
    storageBucket: 'bukuraya-f3a47.firebasestorage.app',
    iosBundleId: 'com.example.bukuRaya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTTT009WV0mTVN_aQSK8iyop5qO5oT0Ok',
    appId: '1:603224733477:ios:af0ad4cdd2a03cea8c8ccc',
    messagingSenderId: '603224733477',
    projectId: 'bukuraya-f3a47',
    storageBucket: 'bukuraya-f3a47.firebasestorage.app',
    iosBundleId: 'com.example.bukuRaya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN9oqcytf5mI1CoTXQW_M47TU8G5kkGA4',
    appId: '1:603224733477:web:76166a30cc6981c58c8ccc',
    messagingSenderId: '603224733477',
    projectId: 'bukuraya-f3a47',
    authDomain: 'bukuraya-f3a47.firebaseapp.com',
    storageBucket: 'bukuraya-f3a47.firebasestorage.app',
    measurementId: 'G-0MFRYLWP5Q',
  );
}
